options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: '.'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-app', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'run', 'deploy', 'fastapi-app',
        '--image', 'gcr.io/$PROJECT_ID/fastapi-app',
        '--platform', 'managed',
        '--region', 'asia-northeast1',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/fastapi-app'